### ISSUE TITLE
Exception in thread Thread-1 (listParser):  error while parsing

### ISSUE THREAD

**Issue by sajjad-ali60** [bsantraigi/YDM#1]
when i paste he youtube playlist link in box and click on parse it gives an error.

Exception in thread Thread-1 (listParser):
Traceback (most recent call last):
  File "C:\Users\HaLF-MenTaL\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner                                                      
    self.run()
  File "C:\Users\HaLF-MenTaL\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run                                                                    
    self._target(*self._args, **self._kwargs)
  File "C:\YDM\yListerFull.py", line 107, in listParser
    final_url, l = crawl(list_url)
  File "C:\YDM\yListerFull.py", line 69, in crawl
    final_url.append('http://www.youtube.com/' + yPL[:yPL_amp])
UnboundLocalError: local variable 'yPL_amp' referenced before assignment

every time when i press on the parse button, the thread number in first line increased by one and no progress of   parse shown

**Comment by wahmadel** [comment]
Solved in my pull request.

**Comment by a-sajjad72** [comment]
> Solved in my pull request.

but those changes are not merged yet. I think @bsantraigi is not maintaining it anymore. @wahmadel  I see you opened two pull requests for this repo. I would also suggest you to merge your changes in your master branch. so that it should be much easier to run the program easily. and one more thing use `yt-dlp` instead of `youtube-dl` because `youtube-dl` is not maintained anymore.

**Comment by mrJurhi** [comment]
> Solved in my pull request.

hi im a new github user, i dunno much about github but i installed program n i get the same error, i looked solved requests, u  wrote 2 request which one is solvation?

**Comment by mrJurhi** [comment]
> Solved in my pull request.

hi i tried ur patch 2 n opened the program but it gave me this error in console again what should i do

Traceback (most recent call last):
  File "C:\Users\Monster\AppData\Local\Programs\Python\Python313\Lib\threading.py", line 1041, in _bootstrap_inner
    self.run()
    ~~~~~~~~^^
  File "C:\Users\Monster\AppData\Local\Programs\Python\Python313\Lib\threading.py", line 992, in run
    self._target(*self._args, **self._kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Monster\Downloads\Compressed\YDM-patch-2\YDM-patch-2\yListerFull.py", line 107, in listParser
    final_url, l = crawl(list_url)
                   ~~~~~^^^^^^^^^^
  File "C:\Users\Monster\Downloads\Compressed\YDM-patch-2\YDM-patch-2\yListerFull.py", line 69, in crawl
    final_url.append('http://www.youtube.com/' + yPL[:yPL_amp])
                                                      ^^^^^^^
UnboundLocalError: cannot access local variable 'yPL_amp' where it is not associated with a value
